version: '3.1'

services:
  db-practica:
    image: postgres
    ports:
      - 5431:5432
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=projectApi
    volumes:
      - /postgres/init.sql:/docker-entrypoint-initdb.d/init.sql